namespace Appalachia.Editing.Core.Operations
{
    public enum StringOperation
    {
        PadLeft,
        PadLeftSpaces,
        PadRight,
        PadRightSpaces,
        RemoveAt,
        RemoveCharacters,
        RemoveString,
        ReplaceCharacters,
        ReplaceString,
        Split,
        SplitAndTakeFirst,
        SplitAndTakeLast,
        Substring,
        SubstringToEnd,
        ToLower,
        ToUpper,
        ToTitleCase,
        Trim,
        TrimStart,
        TrimEnd,
        Append,
        AppendFileName,
        Prepend,
        Set
    }
}
